import os
import logging
from time import strptime, struct_time
import time
import xml.dom.minidom
import itertools


import argparse
from argparse import RawTextHelpFormatter
from csv_tools import csv_safe_string
from robot_output_tools import parse_robot_output_xml


# Nightly run summarizer:
# TODO: Allow multiple roots to be specified.
#
# Sniffers (log message tags):
#   Several log statements are formatted such that, when extracted, they produce a CSV file outputs.
#   To extract, execute:
#       findstr [tag] run_summary.log | cut -f3- -d ' ' > runinfos.csv
#   Currently, they are:
#       Sniffer tag "suitedump "- Log the pass1 suite details:
#       Sniffer tag "testtimedump" - log every Pass1 test case for execution time
#       Sniffer tag "fullrobotparse" - Parse/dump all data from output.xml - (pass1 only, just to cut down on data)
#


class TestData:
    def __init__(self, suite_name, test_name, testtime, fail_msg) -> None:
        self.suite_name = suite_name
        self.test_name = test_name
        self.test_time = testtime
        self.fail_msg = fail_msg
        if not fail_msg is None:
            self.fail_msg = str(fail_msg).splitlines()[0]
        self.tags = ""
        self.count = 0
        self.test_time_rerun = None
        self.fail_msg_rerun = None

        self.failed_endpoint = "Unknown"
        if fail_msg:
            if str(fail_msg).startswith("device_"):
                self.failed_endpoint = str(fail_msg)[0 : (len("device_"))]

    def is_failed(self):
        if self.test_time_rerun:
            if not self.fail_msg_rerun:
                # Passed on rerun
                return False
            return True

        if not self.fail_msg:
            # Passed on first attempt
            return False
        # Failed on first attempt
        return True

    def add_robot_file_data(self, suite_name, suite_dir):
        # logging.debug(f"TODO: Add data from robot file (tags,count) from {suite_dir}, {suite_name}")
        pass


class SuiteData:
    def __init__(self, suite_name, suite_dirname, suite_path) -> None:
        self.suite_name = suite_name
        self.suite_dir = suite_dirname
        self.suite_path = suite_path
        self.testdatas = {}

    def add_testdata(self, testdata: TestData):
        if testdata.test_name in self.testdatas:
            raise AssertionError(
                f"Suite {self.suite_name} Cannot add testdata '{testdata.test_name}' - already present"
            )
        testdata.add_robot_file_data(self.suite_dir, self.suite_name)
        self.testdatas[testdata.test_name] = testdata

    def add_rerun_testdata(self, rerun_testdata: TestData):
        if rerun_testdata.test_name not in self.testdatas:
            raise AssertionError(
                f"Suite {self.suite_name} Cannot add testdata '{rerun_testdata.test_name}' - original missing"
            )

        _testdata = self.testdatas[rerun_testdata.test_name]
        _testdata.fail_msg_rerun = rerun_testdata.fail_msg
        _testdata.test_time_rerun = rerun_testdata.test_time


class SuiteDirData:
    def __init__(self, suite_dirname, suite_parent_dirname=None) -> None:
        self.suite_dirname = suite_dirname
        self.suite_parent_dirname = suite_parent_dirname
        self.suitedatas = {}

    def add_suitedata(self, suitedata: SuiteData):
        if suitedata.suite_name in self.suitedatas:
            raise AssertionError(f"Cannot add suitedata '{suitedata.suite_name}' - already present")
        self.suitedatas[suitedata.suite_name] = suitedata


class RunData:
    def __init__(self, options, source_directory, run_start: struct_time, xunit_xml) -> None:
        self.options = options
        self.source_directory = source_directory
        self.run_start = run_start
        #
        # A note on XML files:
        # - the 'outputxunit.xml' file is what is uploaded to ADO - small, but incomplete (no tags, etc.).
        # - the 'output.xml' is complete, but HUGE.
        self.xunit_xml = xunit_xml

        self.suitedirs = {}

    def add_suitedir(self, suitedir: SuiteDirData):
        if suitedir.suite_dirname in self.suitedirs:
            raise AssertionError(f"Cannot add suitedir '{suitedir.suite_dirname}' - already present")
        self.suitedirs[suitedir.suite_dirname] = suitedir

    def gather_data(self):
        # Sniffer "fullrobotparse" - this reads/parses the 'output.xml' file generated by robot.
        # The data from the 'output.xml' is not currently merged with the data from 'outputxunit.xml'
        if not "rerun" in self.source_directory:
            try:
                robot_output_data = parse_robot_output_xml(self.source_directory)
                robot_output_data.dump_csv("fullrobotparse")
            except Exception:
                logging.exception("CSV dump failed, ignored.")

        for _suite_node in self.xunit_xml.getElementsByTagName("testsuite"):
            # Sniffer "suitedump "- Log the pass1 suite details:
            if not "rerun" in self.source_directory:
                _suite_time_ms = _suite_node.getAttribute("time")
                _fq_dirname = os.path.abspath(self.source_directory)
                _suite_testcount = _suite_node.getAttribute("tests")
                _suite_failures = _suite_node.getAttribute("failures")
                _creat_timestamp = time.strftime("%m/%d/%Y %H:%M:%S", self.run_start)
                # Extract from the log to a CSV with:
                #   findstr suitedump run_summary.log | cut -f3- -d ' ' > runinfos.csv
                logging.info(
                    "suitedump,%s,%s,%s,%s,%s",
                    _suite_testcount,
                    _suite_failures,
                    _creat_timestamp,
                    _fq_dirname,
                    _suite_time_ms,
                )

            _suitedata = None

            for _testcase in _suite_node.getElementsByTagName("testcase"):
                _classname = _testcase.getAttribute("classname")

                # # Normally, _classname == "rootSuiteDirName.[subsuiteDirs.]SuiteName"
                # _pieces = str(_classname).split(".")
                # _tc_parents = ".".join(_pieces[0:-1])
                # _suite_name = _pieces[-1]
                _tc_parents, _suite_name = self.split_parts(_classname)

                # Here, we discover sub-suites as in "Test Teams Room/Shared Mode/01 App Settings", "Shared Mode" is a new sub-suite
                if _tc_parents not in self.suitedirs:
                    _suitedir = SuiteDirData(_tc_parents)
                    self.add_suitedir(_suitedir)

                if _suitedata is None or _suitedata.suite_name != _suite_name:
                    _suitedata = SuiteData(_suite_name, _suitedir.suite_dirname, self.source_directory)
                    _suitedir.add_suitedata(_suitedata)

                _testname = _testcase.getAttribute("name")
                _testtime = _testcase.getAttribute("time")
                _failures = _testcase.getElementsByTagName("failure")
                _fail_message = None
                if _failures.length > 0:
                    # Sanity - only expecting one failure:
                    if _failures.length != 1:
                        raise AssertionError(f"Unexpected - multiple failures:  {_failures.length}")
                    for _failure in _failures:
                        _fail_message = _failure.getAttribute("message")

                # Sniffer "testtimedump" - log every Pass1 test case for execution time
                if not "rerun" in self.source_directory:
                    # Extract from the log to a CSV with:
                    #   findstr testtimedump run_summary.log | cut -f3- -d ' ' > testtimedump.csv
                    _test_failed = "Fail"
                    if _fail_message is None:
                        _test_failed = "Pass"

                    logging.info(
                        "testtimedump,%s,%s,%s,%s,%s",
                        self.source_directory,
                        f"{_test_failed}",
                        _classname,
                        csv_safe_string(_testname),
                        _testtime,
                    )

                _suitedata.add_testdata(TestData(_classname, _testname, _testtime, _fail_message))
                # print(
                #     f"Testcase: {_classname}, Name: {_testname}, FailMessage: {_fail_message}"
                # )
                # break  # DEBUG: ONLY 1st test report

    def split_parts(self, arg: str):
        # Normally, _classname == "rootSuiteDirName.[subsuiteDirs.]SuiteName"
        _pieces = str(arg).split(".")
        _parents = ".".join(_pieces[0:-1])
        _suite_name = _pieces[-1]

        return _parents, _suite_name

    def apply_rerun(self, rerundata):
        for rerun_suite_node in rerundata.xunit_xml.getElementsByTagName("testsuite"):
            # Unwrap the xml to the SuiteDir/Suite/Testcase heierachry:
            for _testcase in rerun_suite_node.getElementsByTagName("testcase"):
                _classname = _testcase.getAttribute("classname")
                _tc_parents, _suite_name = self.split_parts(_classname)

                _suitedata = self.suitedirs[_tc_parents].suitedatas[_suite_name]
                _testname = _testcase.getAttribute("name")
                _testtime = _testcase.getAttribute("time")
                _failures = _testcase.getElementsByTagName("failure")
                _fail_message = None
                if _failures.length > 0:
                    # Sanity - only expecting one failure:
                    if _failures.length != 1:
                        raise AssertionError(f"Rerun - Unexpected - multiple failures:  {_failures.length}")
                    for _failure in _failures:
                        _fail_message = _failure.getAttribute("message")

                _suitedata.add_rerun_testdata(TestData(_classname, _testname, _testtime, _fail_message))
                # print(
                #     f"Testcase: {_classname}, Name: {_testname}, FailMessage: {_fail_message}"
                # )
                # break  # DEBUG: ONLY 1st test report


class RunsSummary:
    def __init__(self, options, source_directorys) -> None:
        self.runs = []
        self.test_summary = {}
        self.options = options
        self.source_directorys = source_directorys

    def is_a_run(self, full_dirname):
        if not os.path.isdir(full_dirname):
            run_directory_ignored(full_dirname, "Directory missing")
            return False

        if not os.path.exists(os.path.join(full_dirname, self.options["outputxunit"])):
            run_directory_ignored(
                full_dirname,
                f"Missing '-outputxunit' file ({self.options['outputxunit']})",
            )
            return False
        return True

    def get_generated_time(self, full_name):
        _xml_logfile = os.path.join(full_name, self.options["outputxml"])
        if not os.path.exists(_xml_logfile):
            # For now, ignore the directory.
            run_directory_ignored(
                full_name,
                f"Missing '-outputxml' file ({self.options['outputxml']})",
            )
            return None

        # We have a run directory. Read the run date from the '-outputxml' file:
        output_xml = xml.dom.minidom.parse(_xml_logfile)

        # Look for 'robot generator=' in documentElement:
        #   <robot generator="Robot 3.2.1 (Python 3.8.5 on win32)" generated="20220805 03:15:59.846" rpa="false">
        # Note: need to convert milliseconds (".nnn") to microseconds (".nnn000")
        generated_ts = output_xml.documentElement.getAttribute("generated") + "000"
        logging.debug("Found 'generated=%s in %s", generated_ts, _xml_logfile)

        try:
            generated_time = strptime(generated_ts, "%Y%m%d %H:%M:%S.%f")
        except ValueError:
            run_directory_ignored(
                full_name,
                f"Unparsible 'generated={generated_ts}' timestamp attribute in robot logfile ({_xml_logfile})",
            )
            return None
        return generated_time

    def get_rundata(self, full_dirname, is_pass1=True):
        if not self.is_a_run(full_dirname):
            return None

        # Read the xunit results file:
        xunit_xml = xml.dom.minidom.parse(os.path.join(full_dirname, self.options["outputxunit"]))

        # We really only need to do this when checking for minimum test counts (in pass 1), but
        #   doing it anyway to verify intact "outputxunit" file.
        _test_elements = xunit_xml.getElementsByTagName("testcase")
        if is_pass1:
            if _test_elements.length < self.options["min_tests"]:
                run_directory_ignored(
                    full_dirname,
                    f'Too few tests reported. Actual:{_test_elements.length}, Required: {self.options["min_tests"]}',
                )
                return None
            # print(f"Found {_test_elements.length} tests")

        generated_time = self.get_generated_time(full_dirname)
        if not generated_time:
            # This run is Rejected!
            return None
        return RunData(self.options, full_dirname, generated_time, xunit_xml)

    def get_runs(self):
        # logging.info("Starting with directory: %s", self.source_directory)

        candidate_run_dirs = {}

        for _source_dir in self.source_directorys:
            _rundata = self.get_rundata(_source_dir)

            if _rundata:
                candidate_run_dirs[_rundata.run_start] = _rundata
            else:
                # for name in [f for f in os.listdir("D:\\IPPHONE\\20111780") if os.path.isdir(f)]:
                # for name in next(os.walk("D:\\IPPHONE\\20111780"))[1]
                for name in next(os.walk(_source_dir))[1]:
                    full_name = os.path.join(_source_dir, name)

                    _rundata = self.get_rundata(full_name)
                    if not _rundata:
                        continue

                    if _rundata.run_start in candidate_run_dirs:
                        run_directory_ignored(
                            full_name,
                            f"WARN: Duplicate run start times as {candidate_run_dirs[_rundata.run_start]}",
                        )
                        continue

                    # candidate looks valid and acceptable, remember it:
                    candidate_run_dirs[_rundata.run_start] = _rundata

                # Always sort the entire candidate list (by run_start timestamp)
                candidate_run_dirs = sort_dict_by_key(candidate_run_dirs, True)

                # print(f"Found {len(candidate_run_dirs)} run directorys")
                if self.options["limit"] > 0:
                    logging.info("Considering only the latest %d run directorys", self.options["limit"])
                    candidate_run_dirs = dict(itertools.islice(candidate_run_dirs.items(), self.options["limit"]))

        # now fetch/parse the data
        for _rundata in candidate_run_dirs.values():
            _rundata.gather_data()

            # Check for pass2 re-run:
            _rerundata = self.get_rundata(os.path.join(_rundata.source_directory, "rerun"), is_pass1=False)
            if _rerundata:
                # There was a re-run, get/merge the rerun data:
                _rerundata.gather_data()
                _rundata.apply_rerun(_rerundata)

            self.runs.append(_rundata)

    def show_pass_fails(self):
        _reports = {}
        for run_data in self.runs:
            for suitedir_key in run_data.suitedirs:
                suitedir = run_data.suitedirs[suitedir_key]
                for suitedata_key in suitedir.suitedatas:
                    suitedata = suitedir.suitedatas[suitedata_key]
                    for testdata_key in suitedata.testdatas:
                        testdata = suitedata.testdatas[testdata_key]
                        _parent_info = f"{suitedir.suite_dirname},{suitedata.suite_name}"
                        if testdata.test_name in _reports:
                            _attempts = _reports[testdata.test_name]["attempts"]
                            _successes = _reports[testdata.test_name]["successes"]
                        else:
                            _attempts = 0
                            _successes = 0

                        _attempts += 1

                        if testdata.test_time_rerun:
                            _attempts += 1

                        if not testdata.is_failed():
                            _successes += 1

                        _reports[testdata.test_name] = {
                            "test_name": str(testdata.test_name),
                            "attempts": _attempts,
                            "successes": _successes,
                            "parent_info": _parent_info,
                            "testtime": testdata.test_time,
                            "fail_reason": testdata.fail_msg,
                            "testtime_rerun": testdata.test_time_rerun,
                            "fail_reason_rerun": testdata.fail_msg_rerun,
                        }

        if self.options["csv"]:
            print("passes,attempts,directory,suite,test,time,failreason,rerun time,failreason_rerun")

        for _report in _reports.values():
            _test_name = _report["test_name"]
            _attempts = _report["attempts"]
            _successes = _report["successes"]
            _parent_info = _report["parent_info"]
            _testtime = _report["testtime"]
            _fail_reason = _report["fail_reason"]
            _testtime_rerun = _report["testtime_rerun"]
            _fail_reason_rerun = _report["fail_reason_rerun"]

            if self.options["csv"]:
                _test_name = csv_safe_string(_test_name)
                _testtime = csv_safe_string(_testtime)
                _fail_reason = csv_safe_string(_fail_reason)
                _fail_reason_rerun = csv_safe_string(_fail_reason_rerun)
                _testtime_rerun = csv_safe_string(_testtime_rerun)
                print(
                    f"{_successes},{_attempts},{_parent_info},{_test_name},{_testtime},{_fail_reason},{_testtime_rerun},{_fail_reason_rerun}"
                )
            else:
                print(
                    f"{_successes} of {_attempts}: Suite:{_parent_info} Test:{_test_name} Time:{_testtime} Fail reason:{_fail_reason} Rerun Time:{_testtime_rerun} Rerun Fail reason:{_fail_reason_rerun}"
                )


def parse_args():
    parser = argparse.ArgumentParser(fromfile_prefix_chars="@", formatter_class=RawTextHelpFormatter)

    # FUTURE: We may want to add a 'ignore rerun' option - most of the Sniffers explicitly do this:
    #   if not "rerun" in self.source_directory:
    #

    parser.add_argument(
        "root_dir",
        nargs="?",
        help="\tLegacy positional argument, Root directory to search for Robot run results\n\tWill be interpreted as a '-d' argument, if specified.\n\n",
    )
    parser.add_argument(
        "-d",
        action="extend",
        nargs="+",
        default=[],
        help="\tList of root directorys to search for Robot run results. Default: '.'\n\n",
    )

    parser.add_argument(
        "-csv",
        default=False,
        # type=int,
        action="store_true",
        required=False,
        help="\tProduce output for a CSV file (commas in text are replaced with '[ACOMMA])'\n\n",
    )
    parser.add_argument(
        "-limit",
        default=0,
        type=int,
        required=False,
        help="\tLimit root directory to search to this many results\n\n",
    )
    parser.add_argument(
        "-min_tests",
        default=0,
        type=int,
        required=False,
        help="\tIgnore candidate runs which do not report at least this many test results\n\n",
    )
    parser.add_argument(
        "-outputxml",
        default="output.xml",
        type=str,
        required=False,
        help="\tXML Robot log results file NAME. Default: 'output.xml'\n\n",
    )

    parser.add_argument(
        "-outputxunit",
        default="outputxunit.xml",
        type=str,
        required=False,
        help="\tXUnit XML results file NAME. Default: 'outputxunit.xml'\n\n",
    )

    parser.add_argument(
        "-loglevel",
        default=logging.getLevelName(logging.DEBUG),
        choices=["debug", "info", "notset"],
        required=False,
        help="\tLogging level verbosity.\n\n",
    )

    parser.add_argument(
        "-logfile",
        default="run_summary.log",
        type=str,
        required=False,
        help="\tThe run_summary log file. Default: '.\\run_summary.log'\n\n",
    )
    return vars(parser.parse_args())


def init_logger(options: dict = None):
    """Initiate logging."""

    _loglevel = logging.DEBUG
    if options["loglevel"]:
        if str(options["loglevel"]).lower() == "info":
            _loglevel = logging.INFO
        elif str(options["loglevel"]).lower() == "debug":
            _loglevel = logging.DEBUG
        elif str(options["loglevel"]).lower() == "notset":
            _loglevel = logging.NOTSET

    logging.basicConfig(
        filename=options["logfile"],
        filemode="w",
        format="%(asctime)s.%(msecs)d %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
        level=_loglevel,
    )
    logger = logging.getLogger("run_summary")

    logging.info("Logging initiated at level: %s", logging.getLevelName(_loglevel))
    return logger


def sort_dict_by_key(d, reverse=False):
    return dict(sorted(d.items(), reverse=reverse))


def run_directory_ignored(directory: str, reason: str):
    logging.info("Run directory ignored: %s, %s", directory, reason)


def main():
    options = parse_args()
    init_logger(options)
    logging.debug("       Raw Options=%s", (str(options)))

    # Adjust legacy arguments (backward compatability):
    if options["root_dir"]:
        options["d"].append(options["root_dir"])
    elif len(options["d"]) < 1:
        options["d"].append(".")
    logging.debug("Normalized Options=%s", (str(options)))

    # Ensure all the 'start' directories are actually directories:
    for _dirname in options["d"]:
        if not os.path.exists(_dirname):
            logging.error("Fatal: File or directory does not exist: %s", _dirname)
            print(f"Fatal: File or directory does not exist: {_dirname}")
            return 1
        if not os.path.isdir(_dirname):
            logging.error("Fatal: Not a directory: %s", _dirname)
            print(f"Fatal: Not a directory: {_dirname}")
            return 1

    summary = RunsSummary(options, options["d"])
    summary.get_runs()
    summary.show_pass_fails()


if __name__ == "__main__":
    main()
